HopamReader/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using HopamModel;
using HopamReader.Infrastructure;
using HopamReader.Models;

namespace HopamReader.Controllers
{
	[Authorize(Roles = "User")]
    public class SongController : Controller
    {
		private readonly ISongDataSource _db;

		public SongController(ISongDataSource db)
		{
			_db = db;
		}

		[HttpGet]
        public ActionResult AddSong()
        {
			var model = new SongViewModel();
			return View(model);
        }

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AddSong(SongViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				if (_db.Songs.FirstOrDefault(I => I.Title == viewModel.Title) == null)
				{
					var song = new Song();
					song.Title = viewModel.Title;
					song.Writer = viewModel.Writer;
					song.Genre = viewModel.Genre;
					song.Tone = viewModel.Tone;
					song.Rhythm = viewModel.Rhythm;
					song.Body = viewModel.Body;
					song.CreatedBy = User.Identity.Name;

					_db.AddSong(song);
					_db.Save();

					return RedirectToAction("index", "home");
				}
				else
				{
					ViewBag.Message = "Bản nhạc này đã có rồi.";
				}
			}

			return View(viewModel);
		}
    }
}

HopamReader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale-1" />
    <meta name="description" content="Chuyển hợp âm, gõ nhịp, tự động di chuyển lời nhạc và hơp âm giúp bạn tập chung đánh Guitar và không bị chi phối bởi những thứ khác. Đó la những chất năng căn bảng của http://hopamreader.azurewebsites.net/ Hãy comment trên trang facebook đễ giúp mình hoàn thiện hơn nhũng chất năng trên. Hỗ trợ những khó khăn trong buổi ban đầu tập chơi Guitar. hopam reader Hopam Reader Guitar Hop Am guitar hop am Hợp âm hợp âm reader hopamreader hopam reader" />
    <title>Hopam Reader Guitar Hop Am guitar hop am Hợp âm hợp âm reader hopamreader hopam reader</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    @Styles.Render("~/Content/themes/base/css", "~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div>
        <div class="float-left">
            <span style="color: #fff; margin: auto">
                @Html.ActionLink("Hopam Reader", "Index", "Home") |
            @Html.ActionLink("Add (+)", "AddSong", "Song") |
            @Html.ActionLink("About", "About", "Home")
            </span>
        </div>
        <div class="float-right">
            <section id="login">
                @Html.Partial("_LoginPartial")
            </section>
        </div>
    </div>
    <div id="body">
        @RenderSection("featured", required: false)
        @RenderBody()
    </div>
    <div style="background-color: #312e2e; margin: 5px">
        <span style="color: #fff; margin: auto">&copy; @DateTime.Now.Year - hopam reader
            <a href="http://www.facebook.com/hopam.reader">Facebook</a>
        </span>
        <!-- Place this tag where you want the +1 button to render. -->
        <div class="g-plusone" data-size="medium" data-annotation="inline" data-width="300"></div>
    </div>
    <!-- Place this tag after the last +1 button tag. -->
    <script type="text/javascript">
        (function () {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
    </script>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-36132974-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/chosen")
    @RenderSection("scripts", required: false)
</body>
</html>